import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PROBES, runProbes } from "./probes.ts";
import { registeredTargets } from "./targets.ts";
import type { TargetReport } from "./adapter.ts";

const here = dirname(fileURLToPath(import.meta.url));
const failures: string[] = [];
const lines: string[] = [];

function out(text = ""): void {
  lines.push(text);
}

function check(claim: string, held: boolean, detail: string): void {
  if (!held) failures.push(claim + " - " + detail);
  console.log((held ? "  ok   " : "  FAIL ") + claim + (detail ? "  [" + detail + "]" : ""));
}

function main(): void {
  const registered = registeredTargets();

  out("# ATP-0002 Conformance Report");
  out("");
  out("Generated by conformance/run.ts.");
  out("");
  out("ATP-0002 reduces to **one substantive rule**: a transition is evaluated under the");
  out("semantics in force *before* it, so a semantic change must be authorised by what it");
  out("replaces. The kernel otherwise leaves the relation free. A conformance suite for");
  out("that claim therefore has to be small: five behavioural probes, one of which is");
  out("the rule itself.");
  out("");
  out("Each probe states the ATP-0002 sentence it tests. A target that fails a probe does");
  out("not conform.");
  out("");
  out("## Targets");
  out("");
  out("| Target | Kind | Expected | Conforms | Failed |");
  out("|--------|------|----------|----------|--------|");

  const reports: Array<{ report: TargetReport; expect: "conforms" | readonly string[] }> = [];
  for (const entry of registered) {
    const { results, failed } = runProbes(entry.target);
    const report: TargetReport = {
      target: entry.target.name,
      description: entry.target.description,
      results,
      conforms: failed.length === 0,
      failed,
    };
    reports.push({ report, expect: entry.expect });
    const expected = entry.expect === "conforms" ? "conforms" : "fails " + entry.expect.join(", ");
    out(
      "| " + report.target + " | " + (entry.expect === "conforms" ? "implementation or control" : "mutant") + " | " + expected + " | " +
        (report.conforms ? "yes" : "**no**") + " | " + (report.failed.length === 0 ? "-" : report.failed.join(", ")) + " |",
    );
  }
  out("");

  // -------------------------------------------------------------------------
  console.log("Conformance");
  const reference = reports[0];
  check(
    "the real kernel/ implementation passes every probe",
    reference.report.conforms,
    reference.report.failed.length === 0 ? "5/5" : reference.report.failed.join(", "),
  );
  const control = reports[1];
  check("the abstract pre-state control passes every probe", control.report.conforms, "the control exists so a failure elsewhere is attributable");

  for (let index = 2; index < reports.length; index++) {
    const { report, expect } = reports[index];
    const expected = expect === "conforms" ? [] : [...expect];
    const actual = [...report.failed].sort();
    const wanted = [...expected].sort();
    check(
      "mutant fails exactly what it should: " + report.target,
      JSON.stringify(actual) === JSON.stringify(wanted),
      "expected " + JSON.stringify(wanted) + ", got " + JSON.stringify(actual),
    );
  }

  const anyMutantPasses = reports.slice(2).some((r) => r.report.conforms);
  check(
    "no mutant conforms, so the suite has discriminating power",
    !anyMutantPasses,
    "a suite that passes everything is worthless",
  );

  // -------------------------------------------------------------------------
  out("## Probes");
  out("");
  out("| Probe | Requirement | Expectation |");
  out("|-------|-------------|-------------|");
  for (const probe of PROBES) {
    out("| " + probe.id + " | " + probe.requirement + " | " + probe.expectation + " |");
  }
  out("");

  out("## Detail");
  out("");
  for (const { report } of reports) {
    out("### " + report.target);
    out("");
    out(report.description);
    out("");
    out("| Probe | Verdict | Detail |");
    out("|-------|---------|--------|");
    for (const result of report.results) {
      out("| " + result.probe + " | " + (result.passed ? "passed" : "**FAILED**") + " | " + result.detail + " |");
    }
    out("");
  }

  out("## What a failure means");
  out("");
  out("- **P2 fails** - the implementation consults the successor's semantics, so a domain");
  out("  can adopt rules that authorise their own adoption. This is the whole kernel rule,");
  out("  and the mutant that fails only P2 is otherwise identical to the control.");
  out("- **P3 fails** - semantic evolution is impossible, which makes P2 vacuous.");
  out("- **P4 fails** - the target rejects everything and passes P2 for the wrong reason.");
  out("- **P5 fails** - the relation is not a relation; acceptance depends on history rather");
  out("  than on the state, input, context and successor.");
  out("");
  out("## Scope");
  out("");
  out("This suite establishes conformance to the **one rule**, not correctness, safety, or");
  out("usefulness. A target can pass all five probes and still lose all your money. What it");
  out("cannot do is pass and then let a domain rewrite its own semantics.");
  out("");

  mkdirSync(here, { recursive: true });
  writeFileSync(join(here, "report.md"), lines.join("\n"), "utf8");
  console.log("");
  console.log("conformance: " + (failures.length === 0 ? "all claims held" : failures.length + " claim(s) FAILED") + " -> conformance/report.md");
  if (failures.length > 0) process.exitCode = 1;
}

main();
