import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { policyDocument } from "../kernel/policy.ts";
import type { TransitionProposal } from "../kernel/types.ts";
import { runProbes } from "../conformance/probes.ts";
import { Chain, OPEN_SEMANTICS, type ChainConfig } from "./chain.ts";
import { actorPriority, arrivalOrder, lowestStateRoot, retainAll, type Selector } from "./selectors.ts";
import { chainConformanceTarget } from "./conformance.ts";

const here = dirname(fileURLToPath(import.meta.url));
const failures: string[] = [];
const lines: string[] = [];

function out(text = ""): void {
  lines.push(text);
}

function check(claim: string, held: boolean, detail: string): void {
  if (!held) failures.push(claim + " - " + detail);
  console.log((held ? "  ok   " : "  FAIL ") + claim + (detail ? "  [" + detail + "]" : ""));
}

function base(selector: Selector): Omit<ChainConfig, "semantics"> & { semantics: ReturnType<typeof policyDocument> } {
  return { id: "chain", semantics: OPEN_SEMANTICS, selector, clock: () => 1 };
}

/**
 * The proposals are IDENTICAL across both runs. Only the order in which the node
 * saw them differs, and the node supplies arrival order itself.
 */
function candidate(actor: string, key: string): TransitionProposal {
  return {
    id: "c-" + actor + "-" + key,
    domain: "chain",
    actor,
    intent: "a competing successor",
    policy: { id: "guard" },
    preconditions: [],
    effects: [{ op: "create", key, value: { actor, key } }],
    evidence: [],
    parents: [],
    createdAt: 1,
  };
}

function runWith(selector: Selector, order: readonly { actor: string; key: string }[]): { selected: string; root: string; committed: boolean } {
  const chain = new Chain({ ...base(selector) });
  for (const entry of order) chain.submit(candidate(entry.actor, entry.key));
  const block = chain.commit();
  return { selected: block ? block.proposalId : "none", root: block ? block.stateRoot : chain.stateRoot, committed: block !== null };
}

function main(): void {
  const forward = [
    { actor: "agent-a", key: "slot/1" },
    { actor: "agent-b", key: "slot/2" },
    { actor: "agent-c", key: "slot/3" },
  ];
  const reverse = [...forward].reverse();

  out("# Single-Writer Chain Skeleton");
  out("");
  out("Generated by chain/run.ts.");
  out("");
  out("ATP-0002 permits several valid successors and does not require canonical selection. This");
  out("skeleton adds exactly two things over a bare Domain - a canonical state root and a");
  out("selection rule - and those are the two things the freeze declares optional. There is no");
  out("consensus, and none is needed to see the point below.");
  out("");
  out("## The same candidates, different selectors");
  out("");
  out("Three competing successors from one parent, submitted in two different orders. A node");
  out("only knows the order in which transitions reached it, so order-dependent selection");
  out("makes two honest nodes disagree.");
  out("");
  out("| selector | order A->B->C | order C->B->A | agrees across arrival order |");
  out("|----------|---------------|---------------|---------------------------|");

  const selectors: Selector[] = [arrivalOrder, lowestStateRoot, actorPriority(["agent-c", "agent-b", "agent-a"]), retainAll];
  const results = new Map<string, { forward: ReturnType<typeof runWith>; reverse: ReturnType<typeof runWith> }>();
  for (const selector of selectors) {
    const f = runWith(selector, forward);
    const r = runWith(selector, reverse);
    results.set(selector.id, { forward: f, reverse: r });
    out(
      "| " + selector.id + " | " + f.selected + " | " + r.selected + " | " + (f.selected === r.selected ? "yes" : "**no**") + " |",
    );
  }
  out("");
  out("| selector | what it does |");
  out("|----------|--------------|");
  for (const selector of selectors) out("| " + selector.id + " | " + selector.description + " |");
  out("");

  const arrival = results.get("arrival-order")!;
  const lowest = results.get("lowest-state-root")!;
  const retained = results.get("retain-all")!;
  const priority = results.get("actor-priority")!;

  check(
    "arrival-order selection makes two nodes disagree when they saw the same candidates in different orders",
    arrival.forward.selected !== arrival.reverse.selected,
    arrival.forward.selected + " against " + arrival.reverse.selected,
  );
  check(
    "a deterministic selector over the same candidate set agrees",
    lowest.forward.selected === lowest.reverse.selected,
    lowest.forward.selected + " against " + lowest.reverse.selected,
  );
  check(
    "an out-of-band priority list is also order-independent",
    priority.forward.selected === priority.reverse.selected && priority.forward.selected === "c-agent-c-slot/3",
    priority.forward.selected + " both ways",
  );
  check(
    "and retaining every branch is permitted, which yields no canonical block",
    retained.forward.committed === false && retained.reverse.committed === false,
    "retain-all committed nothing and left the root at genesis",
  );
  check(
    "the kernel is indifferent to which of these is used",
    [arrival, lowest, priority, retained].every((r) => r.forward.root.length > 0),
    "every run produced a state root; the choice never touched R",
  );

  // -------------------------------------------------------------------------
  console.log("");
  console.log("## The chain client passes ATP-0002 conformance");
  out("## The chain client passes ATP-0002 conformance");
  out("");
  const target = chainConformanceTarget({ id: "chain", selector: lowestStateRoot, clock: () => 1 });
  const { results: probeResults, failed } = runProbes(target);
  out("| probe | verdict | detail |");
  out("|-------|---------|--------|");
  for (const result of probeResults) {
    out("| " + result.probe + " | " + (result.passed ? "passed" : "**FAILED**") + " | " + result.detail + " |");
  }
  out("");
  check("the chain skeleton satisfies all five conformance probes", failed.length === 0, failed.length === 0 ? "5/5" : failed.join(", "));

  // -------------------------------------------------------------------------
  out("## What this establishes");
  out("");
  out("1. **Canonical selection is a choice, and a consequential one.** Two honest nodes that");
  out("   saw the same three valid successors in different orders agree only if the selector is");
  out("   order-independent. The kernel has no opinion, which is exactly what the freeze says.");
  out("");
  out("2. **The skeleton is thin on purpose.** A state root and a selection rule are the whole");
  out("   addition. Consensus, ordering, finality and fees are absent because the reduction work");
  out("   showed the protocol content is not there.");
  out("");
  out("3. **The client passes conformance, including P2.** The semantics live at policy/guard in");
  out("   state, and a semantic change is authorised by the semantics it replaces. That is the one");
  out("   rule the kernel actually imposes, and this is what a shipped client would have to");
  out("   demonstrate.");
  out("");
  out("The remaining question is not the skeleton but whether two independent clients would ever");
  out("agree on an amendment. That is the next experiment.");
  out("");

  mkdirSync(here, { recursive: true });
  writeFileSync(join(here, "report.md"), lines.join("\n"), "utf8");
  console.log("");
  console.log("chain: " + (failures.length === 0 ? "all claims held" : failures.length + " claim(s) FAILED") + " -> chain/report.md");
  if (failures.length > 0) process.exitCode = 1;
}

main();
